name: Compile AMD64 Kernel

on:
  repository_dispatch:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi -f $(docker images -q) 2>/dev/null || true
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install git build-essential libncurses-dev libssl-dev libelf-dev bison bc flex rsync debhelper dpkg-dev fakeroot kmod cpio dwarves lz4 zstd xz-utils curl jq
          sudo -E systemctl daemon-reload
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          sudo -E timedatectl set-timezone Etc/UTC
          sudo -E ntpdate ntp.ubuntu.com 0.pool.ntp.org || true
          sudo -E timedatectl set-ntp true
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create simulated physical disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Download source code
        id: down
        working-directory: /builder
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: |
          df -hT ${PWD}
          export version=$(curl -s https://www.kernel.org | grep -A1 -m1 "stable:" | grep -oP '\d+\.\d+\.\d+')
          echo "KERNEL_VERSION=$version" >> $GITHUB_ENV
          export branch=$(echo "${{ env.KERNEL_VERSION }}" | grep -oP '^\d+\.\d+')
          git clone --depth=1 --branch linux-$branch.y https://github.com/gregkh/linux.git linux
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Add Google BBRv3
        id: bbr
        working-directory: /builder/linux
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: |
          git remote add google-bbr https://github.com/google/bbr.git
          git fetch google-bbr
          git checkout google-bbr/v3
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile Statement
        id: statement
        working-directory: /builder/linux
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: | 
          sed -i '/MODULE_DESCRIPTION/d' net/ipv4/tcp_bbr.c && echo 'MODULE_DESCRIPTION("TCP BBR v3 (Bottleneck Bandwidth and RTT) - Compiled & Optimized by Xiaokailnol");' >> net/ipv4/tcp_bbr.c && tail -n 5 net/ipv4/tcp_bbr.c
          echo "status=success" >> ${GITHUB_OUTPUT}
          
      - name: Update Makefile
        id: makefile
        working-directory: /builder/linux
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: | 
          IFS='.' read -r v p s <<< "${{ env.KERNEL_VERSION }}"
          sed -i "s/^VERSION *=.*/VERSION = $v/" Makefile
          sed -i "s/^PATCHLEVEL *=.*/PATCHLEVEL = $p/" Makefile
          sed -i "s/^SUBLEVEL *=.*/SUBLEVEL = $s/" Makefile          
          echo "status=success" >> ${GITHUB_OUTPUT}
          
      - name: Prepare .config and disable certificate checking
        id: config
        working-directory: /builder/linux
        env:
          git_name: ${{ secrets.git_name }}
          git_password: ${{ secrets.git_password }}
          private_amd64_url: ${{ secrets.private_amd64_url }}
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: | 
          curl -u "$git_name:$git_password" -s -o .config "$private_amd64_url"
          scripts/config --disable SYSTEM_TRUSTED_KEYS
          scripts/config --disable SYSTEM_REVOCATION_KEYS
          make olddefconfig
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Building the Debian kernel package
        id: package
        working-directory: /builder/linux
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: | 
            make bindeb-pkg -j$(nproc) LOCALVERSION=-xiaokailnol-bbrv3
            echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Prepare Firmware Files
        id: prepare
        working-directory: /builder/linux
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: |
            mkdir -p rom
            cp -a linux-*.deb rom/
            cd rom && tar -czvf ${{ env.KERNEL_VERSION }}.tar.gz .
            echo "status=success" >> ${GITHUB_OUTPUT}
      
      - name: Upload Kernel to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS == 'success' && !cancelled() }}
        with:
          tag: kernel_amd64_stable
          artifacts: /builder/linux/rom/${{ env.KERNEL_VERSION }}.tar.gz
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          makeLatest: false
          token: ${{ secrets.GITHUB_TOKEN }}
